# Generated by Django 4.0.3 on 2022-04-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0002_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poster',
            name='id',
        ),
        migrations.AddField(
            model_name='poster',
            name='image_id',
            field=models.IntegerField(default=-1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
