# Generated by Django 4.0.3 on 2022-04-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('cinema', '0003_remove_poster_id_poster_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='id',
            field=models.BigAutoField(auto_created=True, default=-1, primary_key=True, serialize=False,
                                      verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='poster',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
    ]
